

services:
  turingia-server:
    build:
      context: .
      dockerfile: TuringIA.Server/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "5000:5000" # Mapea el puerto 5000 del contenedor al puerto 5000 del host
      - "5001:5001" # Mapea HTTPS
    depends_on:
      - mysqlturingtest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysqlturingtest;Database=turingtestbd;User=alan;Password=contrasenaturingtest;

  mysqlturingtest:
    image: mysql:8.0
    container_name: mysqlturingtest
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: contrasenaturingtest
      MYSQL_DATABASE: turingtestbd
      MYSQL_USER: alan
      MYSQL_PASSWORD: contrasenaturingtest
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
